# -*- coding: utf-8 -*-
"""nwm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuYwJDKGkxSwvCqSnup6wqpoC4quVkrp
"""

def deposit(balance):
  while True:
    try:
      amount = int(input("How much you deposed: "))
      break
    except ValueError:
      print("Error: You must type a number!")
  if amount >0:
    balance += amount
    print(f"You succesfully deposed: {amount}")
  else:
    print(f"You can't deposed: {amount}")
  return balance

def withdraw(balance):
  while True:
    try:
      chose = int(input("How much you want withdraw (minimum is 100czk): "))
      break
    except ValueError:
      print("Error: You must type a number!")
  if chose <= balance:
    if chose >=100:
      balance -= chose
      print("Thank you for using our service, do not forgot to take your card and money")
    else:
      print("You must withdraw 100czk at least")
  else:
    print(f"You don't have enought money for withdrawing: {chose}")
  return balance

balance = 4500
running = True

while running:
    print("\n--- ATM MENU ---")
    print(f"Current Balance: {balance} CZK")

    while True:
      try:
        service = int(input("1: Deposit, 2: Withdraw, 3: Exit\nSelect: "))
        break
      except ValueError:
        print("Error: You must type a number!")
    match service:
        case 1:
            balance = deposit(balance)
        case 2:
            balance = withdraw(balance)
        case 3:
            print("Goodbye! Have a nice day.")
            running = False
        case _:
            print("Invalid choice, try again.")